name: open_shock
description: A flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.8
  nb_utils: ^7.0.4
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1

  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Smart Home
  cached_network_image: ^3.4.0
  dashed_circle: ^0.0.2
  dotted_line: ^3.2.2
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.2
  dio: ^5.1.1
  url_launcher: ^6.1.11
  json_annotation: ^4.8.1
  signalr_core: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.12
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/logos/


