name: Release to Google Play

on:
  release:
    types: [published]  # Only triggers when a release is published

jobs:
  build_and_upload_android_release:
    name: Build and Upload Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2

      # Install dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Prepare Keystore (decode and save it)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./android/app/key.jks

      # Set up key.properties file
      - name: Set up key.properties file
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > $GITHUB_WORKSPACE/android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "storeFile=key.jks" >> $GITHUB_WORKSPACE/android/key.properties

      # Clean previous builds
      - name: Clean previous build artifacts
        run: flutter clean

      # Build release Android App Bundle
      - name: Build release AAB
        run: flutter build appbundle --release

      # Upload the Android App Bundle to Google Play
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: app.openshock.mobile 
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
          track: production
      - name: Archive android app file.
        uses: actions/upload-artifact@v4
        with:
          name: openshock.aab
          path: build/app/outputs/bundle/release/app-release.aab

